### ISSUE TITLE
Link to go from Teams to Player

### ISSUE THREAD

**Issue by francoiducat** [david-sauvage/nba-stats#4]
As a user, on the teams page (https://reverent-mayer-e3d204.netlify.app/#/teams), when I click on a team, it links to the players page (https://reverent-mayer-e3d204.netlify.app/#/players) with the selected team so that I can see its players

**Comment by david-sauvage** [comment]
Thank you @francoiducat for your feedback.
I added a button in the team data table in order to do what you suggested :)
See commit https://github.com/david-sauvage/nba-stats/commit/7ac2721654c33b8016bce5b87c929fb64e9d2830 for more details :)
